apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rc
spec:
  replicas: 3
  selector:
    app: nginx-app
  template:
    metadata:
      name: myapp
      labels:
        app: nginx-app
    spec:
      containers:
        - name: myapp
          image: nginx
          ports:
            - containerPort: 80
