apiVersion: v1
kind: Pod
metadata:
  name: vs-pod
  labels:
    app.kubernetes.io/name: vspod
spec:
  containers:
  - name: vspod
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
