apiVersion: v1
kind: Pod
metadata:
  name: toleration-pod
  labels:
    app.kubernetes.io/name: myapp
spec:
  containers:
  - name: myapp
    image: nginx
  tolerations:
  - key: "app" 
    operator: "Equal"
    value: "blue"
    effect: "NoSchedule"